import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import patientsRouter from "./patients";
import appointmentsRouter from "./appointments";
import encountersRouter from "./encounters";
import bedsRouter from "./beds";
import admissionsRouter from "./admissions";
import labRouter from "./lab";
import prescriptionsRouter from "./prescriptions";
import pharmacyRouter from "./pharmacy";
import drugsRouter from "./drugs";
import billsRouter from "./bills";
import serviceCatalogRouter from "./service-catalog";
import cashierRouter from "./cashier";
import reportsRouter from "./reports";
import inventoryRouter from "./inventory";
import staffRouter from "./staff";
import vitalsRouter from "./vitals";
import radiologyRouter from "./radiology";
import otRouter from "./ot";
import vaccinationsRouter from "./vaccinations";
import consentRouter from "./consent";
import checkupsRouter from "./checkups";
import rosterRouter from "./roster";
import queueRouter from "./queue";
import videosRouter from "./videos";
import notificationsRouter from "./notifications";
import auditRouter from "./audit";
import pdfRouter from "./pdf";
import portalRouter from "./portal";
import rolesRouter from "./roles";
import hospitalSettingsRouter from "./hospital-settings";
import adminReportsRouter from "./admin-reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(patientsRouter);
router.use(appointmentsRouter);
router.use(encountersRouter);
router.use(bedsRouter);
router.use(admissionsRouter);
router.use(labRouter);
router.use(prescriptionsRouter);
router.use(pharmacyRouter);
router.use(drugsRouter);
router.use(billsRouter);
router.use(serviceCatalogRouter);
router.use(cashierRouter);
router.use(reportsRouter);
router.use(inventoryRouter);
router.use(staffRouter);
router.use(vitalsRouter);
router.use(radiologyRouter);
router.use(otRouter);
router.use(vaccinationsRouter);
router.use(consentRouter);
router.use(checkupsRouter);
router.use(rosterRouter);
router.use(queueRouter);
router.use(videosRouter);
router.use(notificationsRouter);
router.use(auditRouter);
router.use(pdfRouter);
router.use(portalRouter);
router.use(rolesRouter);
router.use(hospitalSettingsRouter);
router.use(adminReportsRouter);

export default router;
