export type Icd10Entry = { code: string; label: string };

export const ICD10: Icd10Entry[] = [
  { code: "A09", label: "Infectious gastroenteritis and colitis, unspecified" },
  { code: "B34.9", label: "Viral infection, unspecified" },
  { code: "E11.9", label: "Type 2 diabetes mellitus without complications" },
  { code: "E78.5", label: "Hyperlipidemia, unspecified" },
  { code: "E66.9", label: "Obesity, unspecified" },
  { code: "F41.1", label: "Generalized anxiety disorder" },
  { code: "F32.9", label: "Major depressive disorder, single episode, unspecified" },
  { code: "G43.909", label: "Migraine, unspecified, not intractable, without status migrainosus" },
  { code: "H10.9", label: "Conjunctivitis, unspecified" },
  { code: "H66.90", label: "Otitis media, unspecified, unspecified ear" },
  { code: "I10", label: "Essential (primary) hypertension" },
  { code: "I20.9", label: "Angina pectoris, unspecified" },
  { code: "I25.10", label: "Atherosclerotic heart disease of native coronary artery without angina" },
  { code: "I48.91", label: "Unspecified atrial fibrillation" },
  { code: "I50.9", label: "Heart failure, unspecified" },
  { code: "J00", label: "Acute nasopharyngitis (common cold)" },
  { code: "J02.9", label: "Acute pharyngitis, unspecified" },
  { code: "J03.90", label: "Acute tonsillitis, unspecified" },
  { code: "J06.9", label: "Acute upper respiratory infection, unspecified" },
  { code: "J18.9", label: "Pneumonia, unspecified organism" },
  { code: "J20.9", label: "Acute bronchitis, unspecified" },
  { code: "J45.909", label: "Unspecified asthma, uncomplicated" },
  { code: "J44.9", label: "Chronic obstructive pulmonary disease, unspecified" },
  { code: "K21.9", label: "Gastro-esophageal reflux disease without esophagitis" },
  { code: "K29.70", label: "Gastritis, unspecified, without bleeding" },
  { code: "K59.00", label: "Constipation, unspecified" },
  { code: "K35.80", label: "Unspecified acute appendicitis" },
  { code: "L20.9", label: "Atopic dermatitis, unspecified" },
  { code: "L30.9", label: "Dermatitis, unspecified" },
  { code: "L70.0", label: "Acne vulgaris" },
  { code: "M25.50", label: "Pain in unspecified joint" },
  { code: "M54.5", label: "Low back pain" },
  { code: "M54.2", label: "Cervicalgia (neck pain)" },
  { code: "M79.1", label: "Myalgia" },
  { code: "M19.90", label: "Osteoarthritis, unspecified site" },
  { code: "N18.9", label: "Chronic kidney disease, unspecified" },
  { code: "N20.0", label: "Calculus of kidney" },
  { code: "N30.90", label: "Cystitis, unspecified without hematuria" },
  { code: "N39.0", label: "Urinary tract infection, site not specified" },
  { code: "O80", label: "Encounter for full-term uncomplicated delivery" },
  { code: "R05", label: "Cough" },
  { code: "R07.9", label: "Chest pain, unspecified" },
  { code: "R10.9", label: "Unspecified abdominal pain" },
  { code: "R11.2", label: "Nausea with vomiting, unspecified" },
  { code: "R19.7", label: "Diarrhea, unspecified" },
  { code: "R42", label: "Dizziness and giddiness" },
  { code: "R50.9", label: "Fever, unspecified" },
  { code: "R51", label: "Headache" },
  { code: "R53.83", label: "Other fatigue" },
  { code: "S06.0X0A", label: "Concussion without loss of consciousness, initial encounter" },
  { code: "T78.40XA", label: "Allergy, unspecified, initial encounter" },
  { code: "Z00.00", label: "General adult medical examination without abnormal findings" },
  { code: "Z23", label: "Encounter for immunization" },
];

export function searchIcd10(query: string, limit = 12): Icd10Entry[] {
  const q = query.trim().toLowerCase();
  if (!q) return ICD10.slice(0, limit);
  return ICD10.filter(
    (e) => e.code.toLowerCase().includes(q) || e.label.toLowerCase().includes(q),
  ).slice(0, limit);
}
